[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "crypto"
version = "1.0.0"
dependencies = [
    "setuptools",
    "typer",
]

[project.scripts]
crypto="crypto.crypto_cli:app"
